Feature UI header
training-dgu/langding-page-scss pull request #3
Opened 2023-07-22 17:43 UTC by LeTrungPhong

Feature UI header

2023-07-23 10:34 UTC, DuyTinh2003 requested changes

2023-07-23 10:34 UTC, Duy-Tinh-Dev commented on img/header__icon-logo.svg
không cần đặt tên ảnh theo bem đâu :))

2023-07-23 10:34 UTC, Duy-Tinh-Dev commented on index.html
> +      <header>
đặt tên class vào

2023-07-23 10:34 UTC, Duy-Tinh-Dev commented on sass/app.scss
> +header  {
không select đến thẻ

2023-07-23 10:34 UTC, Duy-Tinh-Dev commented on sass/app.scss
> +        // gap: 30px;
không sài thì delete

2023-07-23 10:34 UTC, DuyTinh2003 commented on img/header__icon-logo.svg
a tạo sẵn folder images rồi mà :(( sao còn tạo img nữa xóa 1 cái

2023-07-23 10:34 UTC, DuyTinh2003 commented on sass/app.css
có install extension prettier chưa.

2023-07-23 10:34 UTC, DuyTinh2003 commented on sass/app.scss
> +    background-color: $main-backgroundcolor;
$main-background-color;

2023-07-23 10:34 UTC, DuyTinh2003 commented on sass/app.scss
> +            color: black;
đặt biến đi e

2023-07-23 10:34 UTC, DuyTinh2003 commented on sass/app.scss
> +            color: white;
này nữa

2023-07-23 10:34 UTC, DuyTinh2003 commented on sass/app.scss
> +        .account__item  {
&__item{
}
chứ

2023-07-23 10:34 UTC, DuyTinh2003 commented on sass/app.scss
> +        .nav__item  {
&__item

2023-07-23 10:34 UTC, DuyTinh2003 commented on sass/_resets.scss
> +@mixin resetlink    {
resetLink

2023-07-23 17:29 UTC, LeTrungPhong commented on sass/app.css
dạ chưa anh

2023-07-24 02:37 UTC, DuyTinh2003 requested changes

2023-07-24 02:37 UTC, DuyTinh2003 commented on sass/app.scss
> +        .nav__item  {
&__item

2023-07-24 02:37 UTC, DuyTinh2003 commented on sass/app.scss
> +        .nav__item:hover  {
&__:hover

2023-07-26 16:46 UTC, merged